.PHONY: All
All: Part1 Part2

.PHONY: Part1
Part1:
	$(info Part 1:)
	rustc part1.rs
	./part1 input.txt

.PHONY: Part2
Part2:
	$(info Part 2:)
	rustc part2.rs
	./part2 input.txt

.NOTPARALLEL:
.SILENT:
