.PHONY: all
all: part1 part2

.PHONY: part1
part1:
	$(info Part 1:)
	rustc part1.rs
	./part1 input.txt

.PHONY: part2
part2:
	$(info Part 2:)
	rustc part2.rs
	./part2 input.txt

.NOTPARALLEL:
.SILENT:
