.PHONY: all
all: part1 part2

.PHONY: part1
part1:
	$(info Part 1:)
	# APL will print an extra newline and I cannot stop that
	./part1.apl -- input.txt | head -n 1

.PHONY: part2
part2:
	$(info Part 2:)
	# APL will print an extra newline and I cannot stop that
	./part2.apl -- input.txt | head -n 1

.NOTPARALLEL:
.SILENT:
