.PHONY: All
All: Part1 Part2

.PHONY: Part1
Part1:
	$(info Part 1:)
	# APL will print an extra newline and I cannot stop that
	./part1.apl -- input.txt | head -n 1

.PHONY: Part2
Part2:
	$(info Part 2:)
	# APL will print an extra newline and I cannot stop that
	./part2.apl -- input.txt | head -n 1

.NOTPARALLEL:
.SILENT:
