.PHONY: all
all: part1 part2

.PHONY: part1
part1:
	$(info Part 1:)
	kotlinc -script part1.kts -- input.txt

.PHONY: part2
part2:
	$(info Part 2:)
	kotlinc -script part2.kts -- input.txt

.NOTPARALLEL:
.SILENT:
