.PHONY: All
All: Part1 Part2

.PHONY: Part1
Part1:
	$(info Part 1:)
	kotlinc -script part1.kts -- input.txt

.PHONY: Part2
Part2:
	$(info Part 2:)
	kotlinc -script part2.kts -- input.txt

.NOTPARALLEL:
.SILENT:
